name: Docker Image Building CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nlianz/auto_dockerimage:latest
    - name: Push the Docker Image
      run: docker login -u nlianz -p ${{ secrets.DOCKER_TOKEN}} && docker push nlianz/auto_dockerimage:latest 
